[workspace]
members = [
    "perf_target",
    "table",
    "variable_storage",
    "graph",
    "macro_lib",
    "macro_use",
    "traits",
    "tests",
    "file_extent",
    "file_table",
]
[profile.release]
debug=true
