[package]
name = "file_table"
version = "0.1.0"
authors = ["BuildTools <nickalexeev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
traits = {path="../traits"}
anyhow = "1.0.34"
thiserror="1.0.22"
